// src/components/AssessmentForm/AssessmentForm.jsx
import { useState } from "react";
import { Link } from "react-router-dom";
import "./AssessmentForm.css";
import ResultsCard from "../ResultsCard/ResultsCard.jsx";
import { API_BASE_URL } from "../../../apiConfig";

// Shown to logged-out users
const LoginPrompt = () => {
  return (
    <div className="login-prompt">
      <div className="form-header">
        <h2>Discover Your Investor Profile</h2>
        <p>
          Sign in to take our comprehensive assessment and receive your
          personalized investment strategy.
        </p>
      </div>
      <Link to="/login" className="prompt-button">
        Sign In to Get Started
      </Link>
    </div>
  );
};

function AssessmentForm({ user }) {
  const [formData, setFormData] = useState({
    age: "",
    income: "",
    emergencyFund: "",
    investmentHorizon: "",
    marketDropResponse: "",
    riskTolerance: "",
  });

  const [isLoading, setIsLoading] = useState(false);
  const [results, setResults] = useState(null);
  const [submitError, setSubmitError] = useState("");

  const handleChange = (event) => {
    const { name, value } = event.target;
    setFormData((prevData) => ({ ...prevData, [name]: value }));
  };

  // Scroll helper to jump to AI panel when user clicks the button
  const handleScrollToAI = () => {
    const panel = document.getElementById("ai-advisor-panel");
    if (panel) {
      panel.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  // Submit → call /api/ai-stock-picks (AI-driven recos + data)
  const handleSubmit = async (event) => {
    event.preventDefault();
    setIsLoading(true);
    setSubmitError("");
    setResults(null);

    try {
      const response = await fetch(`${API_BASE_URL}/api/ai-stock-picks`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        throw new Error("Failed to get AI-powered stock picks");
      }

      const result = await response.json();
      // result: { riskProfile, allocation, aiSummary, aiDisclaimer, aiStocks }
      setResults(result);
    } catch (error) {
      console.error("Error during AI stock picks fetch:", error);
      setSubmitError(
        "We couldn’t generate AI-powered recommendations right now. Please try again in a few minutes."
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handleRetake = () => {
    setResults(null);
    setSubmitError("");
    setFormData({
      age: "",
      income: "",
      emergencyFund: "",
      investmentHorizon: "",
      marketDropResponse: "",
      riskTolerance: "",
    });
  };

  return (
    <section id="assessment" className="assessment-section">
      <div className="form-container">
        {results ? (
          <>
            <ResultsCard
              data={results}
              onRetake={handleRetake}
              onViewAIAdvice={handleScrollToAI}
            />

            {/* 🔥 AI Advisor Panel below results, using aiSummary + aiDisclaimer */}
            <div id="ai-advisor-panel" className="ai-advisor-wrapper">
              {results.aiSummary && (
                <div className="ai-advice-card">
                  <div className="ai-advice-header">
                    <div className="ai-advice-title">
                      <span className="ai-badge">AI Advisor</span>
                      <span className="ai-subtitle">
                        Institutional-style commentary on your AI-selected
                        basket
                      </span>
                    </div>
                    <span className="ai-model-chip">AI generated</span>
                  </div>

                  <div className="ai-advice-body">
                    <p className="ai-advice-text">{results.aiSummary}</p>
                  </div>

                  <div className="ai-advice-footer">
                    <p className="ai-advice-disclaimer">
                      {results.aiDisclaimer ||
                        "This note is generated by an AI model using a restricted internal universe of stocks and your stated risk profile. It is intended purely as an educational, research-style overview and does not constitute a securities recommendation, exhaustive due diligence or registered investment advice. Always perform your own independent analysis or consult a qualified adviser before making investment decisions."}
                    </p>
                  </div>
                </div>
              )}
            </div>
          </>
        ) : user ? (
          <>
            <div className="form-header">
              <h2>Discover Your Investor Profile</h2>
              <p>
                This short assessment will help us understand your risk
                tolerance and financial goals to provide personalized,
                AI-powered stock recommendations.
              </p>
            </div>
            <form className="assessment-form" onSubmit={handleSubmit}>
              <div className="form-group">
                <label htmlFor="age">What is your age?</label>
                <select
                  id="age"
                  name="age"
                  value={formData.age}
                  onChange={handleChange}
                  required
                >
                  <option value="">Select your age range</option>
                  <option value="18-25">18-25</option>
                  <option value="26-35">26-35</option>
                  <option value="36-45">36-45</option>
                  <option value="46-55">46-55</option>
                  <option value="55+">55+</option>
                </select>
              </div>
              <div className="form-group">
                <label htmlFor="income">
                  What is your approximate annual income?
                </label>
                <select
                  id="income"
                  name="income"
                  value={formData.income}
                  onChange={handleChange}
                  required
                >
                  <option value="">Select your income bracket</option>
                  <option value="<5L">Less than ₹5 Lakh</option>
                  <option value="5L-10L">₹5 Lakh - ₹10 Lakh</option>
                  <option value="10L-20L">₹10 Lakh - ₹20 Lakh</option>
                  <option value="20L-50L">₹20 Lakh - ₹50 Lakh</option>
                  <option value=">50L">More than ₹50 Lakh</option>
                </select>
              </div>
              <div className="form-group">
                <label htmlFor="emergencyFund">
                  Do you have an emergency fund for 3-6 months of expenses?
                </label>
                <select
                  id="emergencyFund"
                  name="emergencyFund"
                  value={formData.emergencyFund}
                  onChange={handleChange}
                  required
                >
                  <option value="">Select an answer</option>
                  <option value="yes">Yes, I am covered.</option>
                  <option value="no">No, I am still building it.</option>
                </select>
              </div>
              <div className="form-group">
                <label htmlFor="investmentHorizon">
                  What is your investment horizon?
                </label>
                <select
                  id="investmentHorizon"
                  name="investmentHorizon"
                  value={formData.investmentHorizon}
                  onChange={handleChange}
                  required
                >
                  <option value="">
                    How long do you plan to invest?
                  </option>
                  <option value="1-3 years">Short-term (1-3 years)</option>
                  <option value="3-5 years">Mid-term (3-5 years)</option>
                  <option value="5-10 years">Long-term (5-10 years)</option>
                  <option value="10+ years">
                    Very Long-term (10+ years)
                  </option>
                </select>
              </div>
              <div className="form-group">
                <label htmlFor="marketDropResponse">
                  If your portfolio lost 20% in a month, what would you do?
                </label>
                <select
                  id="marketDropResponse"
                  name="marketDropResponse"
                  value={formData.marketDropResponse}
                  onChange={handleChange}
                  required
                >
                  <option value="">Select your likely reaction</option>
                  <option value="sell-all">Sell all of it</option>
                  <option value="sell-some">Sell some of it</option>
                  <option value="do-nothing">Hold and do nothing</option>
                  <option value="buy-more">
                    See it as a buying opportunity and invest more
                  </option>
                </select>
              </div>
              <div className="form-group">
                <label htmlFor="riskTolerance">
                  Which best describes your investment goal?
                </label>
                <select
                  id="riskTolerance"
                  name="riskTolerance"
                  value={formData.riskTolerance}
                  onChange={handleChange}
                  required
                >
                  <option value="">Select your primary goal</option>
                  <option value="Conservative">
                    Preservation: I want to protect my capital with minimal
                    risk.
                  </option>
                  <option value="Moderate">
                    Balance: I'm willing to take balanced risks for balanced
                    returns.
                  </option>
                  <option value="Aggressive">
                    Growth: I'm willing to take high risks for high potential
                    returns.
                  </option>
                </select>
              </div>

              {submitError && (
                <p className="form-error-message">{submitError}</p>
              )}

              <button
                type="submit"
                className="submit-button"
                disabled={isLoading}
              >
                {isLoading ? "Running AI Analysis..." : "Get My AI Portfolio View"}
              </button>
            </form>
          </>
        ) : (
          <LoginPrompt />
        )}
      </div>
    </section>
  );
}

export default AssessmentForm;
